### ISSUE TITLE
config file crashes GlazeWM on startup

### ISSUE THREAD

**Issue by AetherSky-arch** [warden7383/glazeConfig#1]
GlazeWM can be started again without an issue when reverting to the default config file.

Here's the error log:

[errors.log](https://github.com/user-attachments/files/17482877/errors.log)

**Comment by warden7383** [comment]
Sorry, this config is still running off of glazewm v2 as I haven't gotten the time to update my config to v3
I've updated the readme to let future users know, thanks!
